let shopItemsData = [
  {
    id: "ytfdjgcm",
    name: "Desktop Computers",
    price: 319.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/desktop.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Gaming Computers",
    price: 529.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/desktop_computer.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Laptops",
    price: 199.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/laptop11.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Gaming Laptops",
    price: 559.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/gaming_laptop.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Computer Monitor",
    price: 199.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/monitor.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Computer Accessories",
    price: 59.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/gaming_bundle.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Computer Memory",
    price: 89.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/ram.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Motherboards & CPU's",
    price: 179.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/motherboard.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Graphic Cards",
    price: 239.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/graphics_card.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Hard Drives",
    price: 69.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/harddrive.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "SSD's",
    price: 89.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/ssd.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Computer Cases",
    price: 59.99,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/case.jpg",
  },
];
